apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcheckd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcheckd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webcheckd
    spec:
      containers:
      - name: webcheckd
        image: quay.io/gbsalinetti/webcheckd:latest
        imagePullPolicy: Always
        env:
          - name: URL1
            valueFrom:
              configMapKeyRef:
                key: url1
                name: webcheckd-config
          - name: FROM
            valueFrom:
              secretKeyRef:
                key: from
                name: webcheckd-secret
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: webcheckd-secret
          - name: TO
            valueFrom:
              configMapKeyRef:
                key: to
                name: webcheckd-config
        command: 
          - webcheckd 
          - -url
          - $(URL1)
          - -from
          - $(FROM)
          - -password
          - $(PASSWORD)
          - -to
          - $(TO)
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
            scheme: HTTP
      restartPolicy: Always
              
